#! /bin/bash

for folder in Documents photos Videos sites Music Dropbox dots DCIM
do
	rsync \
		-rbl \
		--size-only \
		--progress \
		--delete \
		--delete-excluded \
		--exclude='.*' \
	/Volumes/1tb/$folder/ 192.168.2.12:/mnt/drive/$folder/
done
exit
