#! /bin/bash

for folder in Documents sites Dropbox dots
do
	rsync \
		-rbl \
		--size-only \
		--progress \
		--delete \
		--delete-excluded \
		--exclude='.*' \
	~/$folder/ pi:/mnt/drive/$folder/
done
exit
