#! /bin/bash

for folder in Documents photos Videos sites Music GMusic MusicOld Dropbox dots Camera
do
	rsync \
		-rbl \
		--size-only \
		--progress \
		--delete \
		--delete-excluded \
		--backup-dir=/Volumes/1tb/"$folder"_old/ \
		--suffix=_`date +%Y_%m_%d_%H%M%S` \
		--exclude='.*' \
	~/$folder/ /Volumes/1tb/$folder/;
done
exit
