#! /bin/bash

for folder in Documents shows video sites photos Videos
do
	rsync \
		-rbl \
		--size-only \
		--progress \
		--delete \
		--delete-excluded \
		--backup-dir=/Volumes/treddell/"$folder"_old/ \
		--suffix=_`date +%Y_%m_%d_%H%M%S` \
		--exclude='.*' \
	~/$folder/ /Volumes/treddell/$folder/;
done
exit
