#! /bin/bash

for folder in Documents photos Videos sites Music
do
	rsync \
		-rbl \
		--bwlimit 1000 \
		--size-only \
		--progress \
		--delete \
		--delete-excluded \
		--backup-dir=/mnt/drive/"$folder"_old/ \
		--suffix=_`date +%Y_%m_%d_%H%M%S` \
		--exclude='.*' \
	~/$folder/ /mnt/drive/$folder/;
done
exit
