#! /bin/bash
rsync \
	-rbl \
	--size-only \
	--progress \
	--delete \
	--delete-excluded \
	--backup-dir=/Volumes/exfat500/mac_old \
	--suffix=_`date +%Y_%m_%d_%H%M%S` \
	--exclude='.*' \
	--exclude='no-backup' \
	--exclude='VirtualBox*' \
	--exclude='vms' \
	--exclude='Library' \
/Users/treddell/ /Volumes/exfat500/mac/;
exit;
